api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  redis:
    address: ":6379"
  firebase_firestore:
    address: ":8080"
  firebase_functions:
    address: ":5001"
  firebase_auth:
    address: ":9099"
  firebase_storage:
    address: ":9199"
  firebase_websocket:
    address: ":54321"
  firebase_logs:
    address: ":4500"

accessLog: {}

providers:
  docker:
    network: nginx-proxy
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: true
  file:
    directory: /app/certificates
    watch: true

log:
  level: DEBUG
