api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  redis:
    address: ":6379"

accessLog: {}

providers:
  docker:
    network: nginx-proxy
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: true
  file:
    directory: /app/certificates
    watch: true

log:
  level: DEBUG
